### ISSUE TITLE
Error in importing 

### ISSUE THREAD

**Issue by DiscordBot-Developer** [Arthurdw/Reaction-Role#2]
there is an error importing repo in Versionhandler.py 

Following is the error code provided by the terminal.
![Screenshot 2021-01-10 143911](https://user-images.githubusercontent.com/77100172/104118796-9f991c00-5351-11eb-9008-745ecc9cae39.png)

Exception has occurred: ImportError
Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
  File "C:\Users\dell\OneDrive\Desktop\Discord bots\Reaction-Role-master\utils\VersionHandler.py", line 27, in <module>
    from git import Repo
  File "C:\Users\dell\OneDrive\Desktop\Discord bots\Reaction-Role-master\utils\__init__.py", line 26, in <module>
    from utils.VersionHandler import VersionHandler
  File "C:\Users\dell\OneDrive\Desktop\Discord bots\Reaction-Role-master\run.py", line 36, in <module>
    from utils import VersionHandler, PrintHandler

please provide me so guidance so that I could remove this error

**Comment by Arthurdw** [comment]
You don't have git installed. (Which is a dependency)
To fix this error install git from [here](https://git-scm.com/downloads) and make sure its added to your path.

**Comment by DiscordBot-Developer** [comment]
Ok thanks for the help
