### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by KdoxT** [Arthurdw/Reaction-Role#3]
Where do I make the command for the bot to do the reaction role message?

**Comment by Arthurdw** [comment]
Hey there.

The bot currently does not work by executing a command. As stated in the [readme](/Arthurdw/Reaction-Role/blob/6872f64/README.md) you have to configure the reaction roles on an existing message. I might make a command that will handle this in the future. But currently, I have a lot of other things to do.

If you know how to code in python you are always able to create a discord.py/UtilsX COG. *(With the proper setup function etc)* And just drop it in the `extensions` folder and reboot the bot. If you write an extension feel free to create a  PR with your extension in the [Bot Extensions repository](https://github.com/Arthurdw/BotExtensions).

So to concretely answer your question, to create a reaction role you *(currently)* don't use a command. To create a reaction role, send a message *(can be anyone, even other bots)*. Then copy that message-id. (if you are unable to do that, make sure that discord developer mode is on in the settings) If you have the id of your message, please follow [these steps](https://github.com/Arthurdw/Reaction-Role/blob/6872f64/README.md#configuring-the-reaction-roles).
