### ISSUE TITLE
Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')]

### ISSUE THREAD

**Issue by MrDmitry1107** [Arthurdw/Reaction-Role#4]

**Comment by Arthurdw** [comment]
Numerous fixes have been provided in [#4159 | discord.py](https://github.com/Rapptz/discord.py/issues/4159).
Feel free to contact me in my discord if you need further assistance. *(https://dc.xiler.net)*.

I'll be closing this issue as it is not code-related. (It's a client-side SSL certificate validation problem, which I can not do anything about)
