### ISSUE TITLE
Bot permissions

### ISSUE THREAD

**Issue by Koli0842** [Arthurdw/Reaction-Role#7]
Hi! I am trying to set this up for my discord server, hosting the bot on my linux server. It start up, connects, and I was able to invite it to my server aswell, I created a new role for my server, copied it's id. I sent a random message to use as testing, then after not seeing results, I tried using the join announcement message with similar configurations. This is how my file currently looks like

```
# -*- coding: utf-8 -*-
"""
MIT License

Copyright (c) 2019-2020 Arthur
.....

Format:
reaction_roles = {
...
}
"""


reaction_roles = {
    1151549620808327299: [
        ("red_car", 1151549651141533696)
    ],
    1151549086051352667: [
        ("eyes", 1151549651141533696),
        (":eyes:", 1151549651141533696),
        ("👀", 1151549651141533696)
    ]
}
```

Logs while the app is running only show a few lines.. Should I be seeing anything here?

```
[23-13-09 19:10:31][INFO] Initializing client...
[23-13-09 19:10:31][INFO] Started loading extensions.
/opt/reaction-role/lib/python3.11/site-packages/utilsx/discord/shorter.py:82: RuntimeWarning: coroutine 'BotBase.load_extension' was never awaited
  self.load_extension(extension)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[23-13-09 19:10:31][INFO] Successfully loaded ReactionLogger
[23-13-09 19:10:31][INFO] Successfully loaded ReactionRoles
2023-09-13 19:10:31 INFO     discord.client logging in using static token
2023-09-13 19:10:32 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: ad3b440828fda4a61ed882c924ba78f6).
[23-13-09 19:10:34][INFO] Currently running on v39!
```

I was wondering if I set up permissions on the discord bot page right? Can you please provide some examples?

Also, even from the examples I am unsure which is the proper way to configure emoji reacts. Do I use the name of it, the syntax how I can type it, or the UTF-8 character? My best guess is the first one, but apparently I am not having massive success currently.. :D

**Comment by Arthurdw** [comment]
Hey there @Koli0842, thank you for reporting this. Seems like discord.py updated their api to make cogs being loaded asynchronously.

This issue has been resolved in the latest commit. If you are still experiencing issues with this, please re-open this ticket.

Once again, thank you for reporting this and have a great day! <3

**Comment by Koli0842** [comment]
Thank you for your quick work! Indeed the bot is now working as expected. Turns out the ~3 permissions I've given the bot were enough aswell. Thanks for your great job and free software!

Maybe a bonus question, if you're familiar with Linux, the systemd unit I created for the app works fine, but looks like the logs directly from the bot code don't appear properly in the sytem journal. When I run it directly from a python venv, I can see it just fine, but through systemd / journalctl, it appears as following:

```
systemd[1]: Started Discord Reaction Roles Bot.
python[831944]: [10B blob data]
python[831941]: [50B blob data]
python[831941]: [55B blob data]
python[831941]: [2023-09-18 01:19:29] [INFO    ] discord.client: logging in using static token
python[831941]: [2023-09-18 01:19:30] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ).
python[831941]: [61B blob data]
python[831941]: [53B blob data]
```

Do you think it's a config issue, or perhaps the logging lib and the way colors are done is confusing the journal?

**Comment by Arthurdw** [comment]
Don't know, In this project I'm using my deprecated library utilsx. So it is probably because of an issue in there, I'm not planning on resolving this issue tho since all of this code is from about 3 years ago and not personally used anymore. If you want to fix this yourself feel free to do so, and create a PR for it.

Anyway, enjoy the rest of your day ^^
